name: 'code_review'
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string
permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Infogain-GenAI/AutoReviewer@ignis
        id: InfogainPrReview
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          model_name: ${{ secrets.MODEL_NAME }}
          exclude_files: '*.json, *.md, *.yml, *.razor'
          model_temperature: ${{ secrets.MODEL_TEMPERATURE }}
          pr_number: ${{ inputs.pr_number }}
